hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/bills/**

        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposits/**

server:
  port: 8989

